option compress=yes;
libname sas_out "/opt/data/datamain/MLS/sas_dataset/";
libname folder "./";

proc contents data=sas_out.all_residentialproperty_2011 noprint out=ctnt_1(keep=name length rename=(length=residentialproperty)); run;
proc sort; by name; run;
proc contents data=sas_out.all_rentals_2011 noprint out=ctnt_2(keep=name length rename=(length=rentals)); run;
proc sort; by name; run;
proc contents data=sas_out.all_lotsandland_2011 noprint out=ctnt_3(keep=name length rename=(length=lotsandland)); run;
proc sort; by name; run;
proc contents data=sas_out.all_commercial_2011 noprint out=ctnt_4(keep=name length rename=(length=commercial)); run;
proc sort; by name; run;
proc contents data=sas_out.all_detachedsingle_2011 noprint out=ctnt_5(keep=name length rename=(length=detachedsingle)); run;
proc sort; by name; run;
proc contents data=sas_out.all_attachedsingle_2011 noprint out=ctnt_6(keep=name length rename=(length=attachedsingle)); run;
proc sort; by name; run;
proc contents data=sas_out.all_mobilehomes_2011 noprint out=ctnt_7(keep=name length rename=(length=mobilehomes)); run;
proc sort; by name; run;
proc contents data=sas_out.all_twotofour_2011 noprint out=ctnt_8(keep=name length rename=(length=twotofour)); run;
proc sort; by name; run;
proc contents data=sas_out.all_residentialrental_2011 noprint out=ctnt_9(keep=name length rename=(length=residentialrental)); run;
proc sort; by name; run;
proc contents data=sas_out.all_deededparking_2011 noprint out=ctnt_10(keep=name length rename=(length=deededparking)); run;
proc sort; by name; run;
proc contents data=sas_out.all_vacantland_2011 noprint out=ctnt_11(keep=name length rename=(length=vacantland)); run;
proc sort; by name; run;
proc contents data=sas_out.all_multifamily_2011 noprint out=ctnt_12(keep=name length rename=(length=multifamily)); run;
proc sort; by name; run;
proc contents data=sas_out.all_officetech_2011 noprint out=ctnt_13(keep=name length rename=(length=officetech)); run;
proc sort; by name; run;
proc contents data=sas_out.all_business_2011 noprint out=ctnt_14(keep=name length rename=(length=business)); run;
proc sort; by name; run;
proc contents data=sas_out.all_mixeduse_2011 noprint out=ctnt_15(keep=name length rename=(length=mixeduse)); run;
proc sort; by name; run;
proc contents data=sas_out.all_retailstores_2011 noprint out=ctnt_16(keep=name length rename=(length=retailstores)); run;
proc sort; by name; run;
proc contents data=sas_out.all_instuttodevelop_2011 noprint out=ctnt_17(keep=name length rename=(length=instuttodevelop)); run;
proc sort; by name; run;
proc contents data=sas_out.all_industrial_2011 noprint out=ctnt_18(keep=name length rename=(length=industrial)); run;
proc sort; by name; run;

data folder.var_list;
merge ctnt_1 - ctnt_18;
by name;
run;
